references:
  build_docker_image: &build_docker_image
    # Environment variables:
    # In context: DOCKER_USER, DOCKER_PASS
    # In job: BUILD_CONTEXT, IMAGE
    docker:
    - image: "docker:18"
    steps:
    - run:
        name: Install local git and ssh client
        command: apk add --no-cache git openssh-client
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Docker Auth
        command: echo "${DOCKER_PASS}" | docker login --password-stdin --username "${DOCKER_USER}"
    - checkout
    - run:
        name: Build and push docker image
        command: |
          # we need to check if there were changes in BUILD_CONTEXT
          # `git diff-tree ..` will show all files changed in current commit
          # `awk ..| sed ..` will print only directories
          # `grep -qxF` will success if BUILD_CONTEXT is found in directories
          # grep options:
          #  -q: Quiet. Return 0 if PATTERN is found, 1 otherwise
          #  -x: Match whole lines only
          #  -F: PATTERN is a literal (not regexp)
          echo ========== Current dir
          pwd; ls -la
          echo ========== Changed files in the last commit
          git diff-tree --no-commit-id --name-only -r HEAD
          echo ========== Changed directories in the last commit
          git diff-tree --no-commit-id --name-only -r HEAD \
          | awk '/\// {print}' | sed 's/\/.*//' \
          | sort | uniq
          if git diff-tree --no-commit-id --name-only -r HEAD \
             | awk '/\// {print}' | sed 's/\/.*//' \
             | grep -qxF "${BUILD_CONTEXT}"; then
            TAG=$(cat ${BUILD_CONTEXT}/tag)
            docker build ${BUILD_CONTEXT} --tag "${IMAGE}:${TAG}"
            docker tag "${IMAGE}:${TAG}" "${IMAGE}:latest"
            docker push "${IMAGE}:${TAG}"
            docker push "${IMAGE}:latest"
          else
            echo "No changes in ${BUILD_CONTEXT}/, skipping build"
          fi



version: 2

workflows:
  version: 2
  build_docker_images:
    jobs:
    - sshct:
        context: gorilych
    - go-andrey:
        context: gorilych
    - dst:
        context: gorilych
    - httpbin:
        context: gorilych
    - deploy_httpbin:
        requires:
        - httpbin


jobs:
  sshct:
    environment:
      BUILD_CONTEXT: sshct
      IMAGE: gorilych/sshct
    <<: *build_docker_image
  go-andrey:
    environment:
      BUILD_CONTEXT: go-andrey
      IMAGE: gorilych/go-andrey
    <<: *build_docker_image
  dst:
    environment:
      BUILD_CONTEXT: dst
      IMAGE: gorilych/dst
    <<: *build_docker_image
  httpbin:
    environment:
      HTTBIN_GIT_TAG: v0.4.1
      BUILD_CONTEXT: httpbin
      IMAGE: gorilych/httpbin
    <<: *build_docker_image
  deploy_httpbin:
    docker:
    - image: alpine/git:1.0.7
    steps:
    - checkout
    - run:
        name: update image tag in httpbin-config-repo
        environment:
          CONFIG_REPO: git@github.com:scalio/httpbin-config-repo.git

          # CONFIG_REPO_SSH_KEY64: from CircleCI project
          VALUES_FILE: values-httpbin.scaliolabs.com.yaml
          GIT_SSH_COMMAND: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
        command: |
          IMAGE_TAG=$(cat tag)
          mkdir -p ~/.ssh/
          . > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -n "${CONFIG_REPO_SSH_KEY64}" | base64 -d >> ~/.ssh/id_rsa
          git clone ${CONFIG_REPO} __config_repo__ && cd __config_repo__
          sed -i 's/^    tag:.*/    tag: '${IMAGE_TAG}'/' ${VALUES_FILE}
          git config user.name "CircleCI/${CIRCLE_PROJECT_USERNAME}"
          git config user.email ''
          git commit ${VALUES_FILE} -F- <<-EOFMESSAGE
          set image tag to ${IMAGE_TAG}

          Commit from CircleCI triggered by
           build: ${CIRCLE_BUILD_URL}
           commit: ${CIRCLE_SHA1}
           tag: ${CIRCLE_TAG}
           branch: ${CIRCLE_BRANCH}
           repo: ${CIRCLE_REPOSITORY_URL}
           user: ${CIRCLE_PROJECT_USERNAME}
          EOFMESSAGE
          git push

